dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
env: 
- DJANGO=2.1.7 DB=sqlite
before_install: 
- cd AIM_GAMES_PLATFORM
install: 
- pip install -r ../requirements.txt
script: 
- python manage.py test
  
branches:
  only:
  - master3
  - develop
