# Generated by Django 2.1.7 on 2019-04-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0003_auto_20190411_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(verbose_name='Coins')),
                ('expirationDate', models.DateTimeField(verbose_name='Expiration Date')),
                ('starDate', models.DateTimeField(verbose_name='Start Date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('maxCoins', models.IntegerField(verbose_name='Max Coin')),
                ('coinsGain', models.IntegerField(verbose_name='Coin Coin')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriptionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.SubscriptionModel'),
        ),
    ]
