# Generated by Django 2.1.7 on 2019-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0006_auto_20190425_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
