# Generated by Django 2.1.7 on 2019-04-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0007_auto_20190428_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='subscriptionModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AIM_GAMES.SubscriptionModel'),
        ),
    ]
