# Generated by Django 2.1.7 on 2019-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0008_auto_20190428_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(null=True, verbose_name='Photo'),
        ),
    ]
