# Generated by Django 2.1.7 on 2019-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0009_auto_20190429_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(blank=True, default='', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
