# Generated by Django 2.1.7 on 2019-04-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0009_curriculum_featured'),
        ('AIM_GAMES', '0010_auto_20190429_1628'),
    ]

    operations = [
    ]
