# Generated by Django 2.1.7 on 2019-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0011_merge_20190429_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadPrice', models.IntegerField(default=0, verbose_name='Thread Price')),
                ('jobOfferPrice', models.IntegerField(default=0, verbose_name='Job Offer Price')),
                ('challengePrice', models.IntegerField(default=0, verbose_name='Challenge Price')),
                ('defaultMaxCoins', models.IntegerField(default=10, verbose_name='Default maximum coins')),
                ('coinsPrice', models.FloatField(default=5, verbose_name='Coins price')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='coinsGain',
            field=models.IntegerField(verbose_name='Coins Gain'),
        ),
    ]
