# Generated by Django 2.1.7 on 2019-05-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0012_auto_20190501_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemvariables',
            old_name='coinsPrice',
            new_name='directPurchaseCoinsPrice',
        ),
        migrations.AddField(
            model_name='systemvariables',
            name='directPurchaseCoinsQuantity',
            field=models.IntegerField(default=5, verbose_name='Coins quantity on purchase'),
        ),
    ]
