# Generated by Django 2.1.7 on 2019-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0014_auto_20190501_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='images',
            field=models.TextField(blank=True, verbose_name='images'),
        ),
    ]
