# Generated by Django 2.1.7 on 2019-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0020_auto_20190520_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='AIM_GAMES.Tag', verbose_name='tags'),
        ),
    ]
