# Generated by Django 2.1.7 on 2019-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0021_auto_20190520_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='AIM_GAMES.Tag'),
        ),
    ]
