# Generated by Django 2.1.7 on 2019-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0023_auto_20190520_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='transactionStarted',
            field=models.BooleanField(default=False, verbose_name='Transaction Started'),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='description_eng',
            field=models.CharField(default='', max_length=60, verbose_name='Description_ENG'),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='name_eng',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Name_ENG'),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='description',
            field=models.CharField(default='', max_length=60, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
