# Generated by Django 2.1.7 on 2019-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0024_auto_20190523_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='name_eng',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name_ENG'),
        ),
    ]
