# Generated by Django 2.1.7 on 2019-05-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0025_auto_20190523_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='transactionStarted',
        ),
    ]
