# Generated by Django 2.1.7 on 2019-05-23 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0026_remove_business_transactionstarted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='subscriptionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AIM_GAMES.SubscriptionModel'),
        ),
    ]
